export const ENGINES = [
  { abbr: 'Ms', name: 'MySQL', color: '#E6922E' },
  { abbr: 'Pg', name: 'PostgreSQL', color: '#336791' },
  { abbr: 'Re', name: 'Redis', color: '#8B1A1A' },
  { abbr: 'Sl', name: 'SQLite', color: '#7B3FA0' },
  { abbr: 'Mg', name: 'MongoDB', color: '#116149', soon: true },
  { abbr: 'Ss', name: 'SQL Server', color: '#9B9B9B', soon: true },
] as const

export const FEATURES = [
  {
    title: 'Pro-grade SQL editor',
    desc: 'Multiple query tabs per database, schema-aware autocomplete, multi-statement execution, SQL formatter, query variables with :placeholders, EXPLAIN visualizer, and saved snippets per engine.',
    stat: 'Full',
    statLabel: 'SQL IDE built in',
    gradient: ['#0078d4', '#00b4d8'],
    icon: 'code',
    highlights: ['Multi-tab queries', 'Autocomplete', 'EXPLAIN', 'Snippets'],
    isNew: true,
    newLabel: 'Now with query tabs',
  },
  {
    title: 'Blazing-fast data grid',
    desc: 'Virtual-scrolled grid that renders millions of rows at 60fps. Inline editing, drag-to-select, sticky columns, column stats, row comparison, and copy-paste.',
    stat: '60',
    statLabel: 'fps with 100K+ rows',
    gradient: ['#7B3FA0', '#c084fc'],
    icon: 'edit',
    highlights: ['Virtual scroll', 'Inline edit', 'Drag select', 'Stats'],
  },
  {
    title: 'SSH tunnel & terminal',
    desc: 'Connect to remote databases through SSH tunnels with password or key auth. Plus a built-in SSH terminal with xterm.js - multi-tab sessions, keepalive, auto-reconnect, and saved credentials.',
    stat: 'Built-in',
    statLabel: 'SSH terminal',
    gradient: ['#059669', '#4ec9b0'],
    icon: 'terminal',
    highlights: ['SSH tunnel', 'SSH terminal', 'Key auth', 'Multi-tab'],
    isNew: true,
    newLabel: 'New feature',
  },
  {
    title: 'Secure by default',
    desc: 'OS keychain credential storage, SSL/TLS with custom certificates, built-in data masking to auto-hide PII columns like email and passwords. Zero passwords on disk.',
    stat: 'Zero',
    statLabel: 'passwords on disk',
    gradient: ['#14b8a6', '#5eead4'],
    icon: 'shield',
    highlights: ['OS keychain', 'SSL/TLS', 'Data masking', 'Read-only mode'],
  },
  {
    title: 'Keyboard-first workflow',
    desc: '36 keyboard shortcuts, command palette, multi-connection tabs, query tabs with Cmd+T/W, session restore - hands never leave the keyboard.',
    stat: '36',
    statLabel: 'shortcuts',
    gradient: ['#d97706', '#fbbf24'],
    icon: 'keyboard',
    highlights: ['Cmd+P palette', 'Tab restore', 'Quick switch'],
  },
  {
    title: '4 engines, one app',
    desc: 'MySQL, PostgreSQL, SQLite, and Redis with unified UI. Schema diff, foreign key viewer, and engine-specific query support built in.',
    stat: '4',
    statLabel: 'engines',
    gradient: ['#dc2626', '#f87171'],
    icon: 'database',
    highlights: ['MySQL', 'PostgreSQL', 'SQLite', 'Redis'],
  },
  {
    title: 'Import & export everything',
    desc: 'Export to CSV, JSON, SQL. Import CSV with column mapping. Copy rows as PHP, Python, Go, Ruby, YAML. Full database backup & restore.',
    stat: '6+',
    statLabel: 'export formats',
    gradient: ['#e855a0', '#fb7185'],
    icon: 'feather',
    highlights: ['CSV', 'JSON', 'SQL', 'Code copy'],
  },
  {
    title: 'Metrics Board',
    desc: 'Write SQL, pick a chart type, and see live visualizations on a dashboard. Multiple layouts, full-screen detail view, and export to PDF - your data, always up to date.',
    stat: '5',
    statLabel: 'chart types',
    gradient: ['#06b6d4', '#22d3ee'],
    icon: 'chart',
    highlights: ['5 chart types', 'PDF export', 'Auto-refresh', '4 layouts'],
  },
] as const

export const PRICING = [
  {
    name: 'Free',
    price: '$0',
    period: 'forever',
    desc: 'All features included - no limits, no account required',
    features: [
      'MySQL, PostgreSQL, SQLite, Redis',
      'SSH terminal & tunnel support',
      'Multi-tab SQL editor',
      'Inline cell editing & data grid',
      'Export to CSV, JSON, SQL',
      'Metrics Board with charts',
      '36+ keyboard shortcuts',
      'Dark & light themes',
    ],
    cta: 'Download Free',
    highlight: false,
  },
  {
    name: 'Pro',
    price: '$8',
    period: '/month',
    desc: 'For developers who work with multiple databases daily',
    features: [
      'Unlimited connections',
      'SSH tunnel, terminal & SSL',
      'Export to CSV, JSON, SQL',
      'Full query history',
      'Unlimited query tabs & saved queries',
      'Metrics Board with auto-refresh',
    ],
    cta: 'Start 14-day Free Trial',
    highlight: true,
  },
] as const

export const STATS = [
  { value: 4, suffix: '+', label: 'DB engines' },
  { value: 2, suffix: 's', label: 'Cold start' },
  { value: 60, suffix: 'fps', label: 'Scroll perf' },
  { value: 80, suffix: 'MB', label: 'RAM usage' },
] as const

export const DOWNLOAD_LINKS = {
  macArm: 'https://github.com/GetDibiku/dibiku/releases/download/v0.3.0/Dibiku_0.3.0_aarch64.zip',
  macIntel: '#',
  windows: '#',
  linuxDeb: '#',
  linuxAppImage: '#',
} as const
